### PR TITLE
adding embedded directory option for startup for OSX #53

### PR DESCRIPTION
**Pull request by kristofb**
I adapted the a little the code from Peter, in order to be able to merge on the latest commit in master.
I adapted the code so now, JRE 8+ are accepted, by setting proper libjli.dylib path.
This enables:
- Max 8 beta runtime to find and use JRE 8+ stored in max-mxj package directory
(Max 8 doesn't search for java outside of mxj, so its fine to detect JRE)

This doesn't enable:
- Use of old JRE 6 as embedded JRE. But it doesn't change the behaviour of mxj when nothing is embedded.

**Comments from Peter Slack (I used his merge request as a base to start mine), still valid:**
I've added an option to embedd a jre directly in the max-mxj packages file for OSX
the directory jre should be placed in max-mxj package directory
it should point to the base of an installed jre or copy the jre into this directory
the option looks for jre/Contents/Home to exist
this only works for 64 bit mode, there is no 32 bit embedded option for OSX
I would also like to merge in the changes from the latest mxj and windows embedd option will follow

### CODE REVIEW

**Comment by tap** [comment]
Thanks for the PR @kristofb -- Do you have a set of detailed instructions that we could use to test the work that you've done? Both to test the new functions and to test the that old functionality worked?

Once we have that we can try to schedule a test and then (assuming success) go ahead with merging.

Cheers,
  Tim

**Comment by kristofb** [comment]
**Original reasons of changes:**
At the moment, on OS X, mxj in Max 8 or in s standalone requires a JDK to be installed in order to start the JVM. This is particularly annoying when we want to distribute a standalone built from Max. Only JAVA developers have a JDK installed and downloading it is much more painful than just installing a JRE.

**Purpose of the changes (OS X only):**
The purpose of the changes is to address the following:
- being able to use Max 8 with JRE (internet plugin) installed only. Thus, this will not allow the max programmer to compile java classes.
- being able to use Max 8 with a JDK (same as now)
- being able to build a standalone which will use an existing JRE (internet plugin)
- being able to build a standalone which will use an installed JDK (same as now)

And also, a particularly interesting point for distributing an app:
- being able to build a standalone which will use an embedded JRE, so the application is not depending on a third party component not installed by default on OSX.

Changes done:
- Merging the work prepared by Peter J Slack
- Adapting it to allow proper java detection by mxj_safe extension, and by mxj and mxj~

For that purpose, I moved all the java detection into the common code of all three objects: JavaHomeOsx.c

I improved it to allow proper detection of JDK (first), then JRE.
I cached the detected result in order to avoid checking too many times the same thing.


Tests performed, results as expected:
- Compilation of new version of mxj_safe mxj mxj~

Virgin OSX 10.13, Java internet plugin installed (JRE):
- Max 8 standard 32bits  => No java detected
- Max 8 32bits with new mxj_safe mxj mxj~ => No java detected

- Max 8 standard 64bits  => No java detected
- Max 8 64bits with new mxj_safe mxj mxj~ => Java JRE detected, mxj functional

Virgin OSX 10.13, JDK 9.0.4 installed:
- Max 8 standard 32bits  => No java detected
- Max 8 32bits with new mxj_safe mxj mxj~ => No java detected

- Max 8 standard 64bits  => Java JDK detected, mxj functional
- Max 8 64bits with new mxj_safe mxj mxj~ => Java JDK detected, mxj functional

- Standalone 64 bits, JRE 8 embedded with new mxj_safe mxj mxj~ => Java JRE 8 detected, mxj functional

**Comment by kristofb** [comment]
**Notes about embedding JRE into a standalone APP, for documentation purpose:**
The full content of JRE installation folder /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin must be included, and renamed "jre".
Then, the embedded JRE folder structure will look like:

MyApp.app/Contents/Resources/C74/packages/max-mxj/jre
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/Frameworks
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/Home
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/Home/bin
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/Home/lib
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/Home/man
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/MacOS
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/Plugins
MyApp.app/Contents/Resources/C74/packages/max-mxj/jre/Contents/Resources

**Comment by kristofb** [comment]
Hi Tim,

I performed some tests and corrections.
The changes have been added to the merge request.
I added as comments explanations and my tests results.


Best regards
Chris

Le 15/02/2018 à 22:51, Timothy Place a écrit :

**Comment by tap** [comment]
Thanks @kristofb -- I'll initiate a conversation about how we want to think about merging this pull request.

I haven't fully grok'd everything here, but I do have a few questions that I'll need to answer (maybe you can help?):

* You speak of this with regards to Max 8, will these changes negatively impact users of the package on Max 7?
* Is there feature parity/disparity with what happens on Windows? It looks like these changes are all on the Mac (unless I read the diff too quickly). Keeping the platforms in sync is a high priority for us.
* Do you mind communicating on some of this via email? I know it is confusing but Max 8 discussions are potentially sensitive as we have not released the product yet (despite the watered-down preview embedded in Live 10). My email address is tim@cycling74.com.

Thanks again

**Comment by pslack** [comment]
Hi Kristof and Tim .. I've been working on other projects so haven't chimed in.  I have a couple of things to add to the thought process and the wants, first I still owe a windows version, this was what was holding up my original PR and my fault for not being on the ball here.  Please cc me on the discussion thread in email ( pslack@wavedna.com )

I feel there is another use case not covered and that is to use mxj embedding in an AMXD, this is particularly of interest to me beyond the standalone use case just to be transparent.  In this use case I would probably install the embedded java outside of the .app bundle in the user packages folder.  For a standalone it is fine to put the embedded java inside the bundle but for AMXD I'm hoping that the user package area takes precedence over the stock package provided inside the Max.app

**Comment by jeremybernstein** [comment]
Closing at user's request (in order to make way for a new request)

**Pull request closed without merging**
